<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <!-- Emulate the package being a NuGet dependency: -->
  <Import Project="../../../src/Swallow.MSBuild.Node/build/Swallow.MSBuild.Node.props" />
  <Import Project="../../../src/Swallow.MSBuild.Node/build/Swallow.MSBuild.Node.targets" />

</Project>
